# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_lab1.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RGB_2_YCbCr_2_RGB(object):
    def setupUi(self, RGB_2_YCbCr_2_RGB):
        RGB_2_YCbCr_2_RGB.setObjectName("RGB_2_YCbCr_2_RGB")
        RGB_2_YCbCr_2_RGB.resize(830, 515)
        self.centralwidget = QtWidgets.QWidget(RGB_2_YCbCr_2_RGB)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_selectF = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_selectF.setGeometry(QtCore.QRect(0, 0, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_selectF.setFont(font)
        self.pushButton_selectF.setObjectName("pushButton_selectF")
        self.pushButton_rgb2ycbcr = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_rgb2ycbcr.setGeometry(QtCore.QRect(0, 200, 131, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_rgb2ycbcr.setFont(font)
        self.pushButton_rgb2ycbcr.setObjectName("pushButton_rgb2ycbcr")
        self.pushButton_ycbcr2rgb = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ycbcr2rgb.setGeometry(QtCore.QRect(0, 270, 131, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_ycbcr2rgb.setFont(font)
        self.pushButton_ycbcr2rgb.setObjectName("pushButton_ycbcr2rgb")
        self.labelImageBase = QtWidgets.QLabel(self.centralwidget)
        self.labelImageBase.setGeometry(QtCore.QRect(140, 0, 220, 220))
        self.labelImageBase.setFrameShape(QtWidgets.QFrame.Panel)
        self.labelImageBase.setText("")
        self.labelImageBase.setScaledContents(False)
        self.labelImageBase.setWordWrap(False)
        self.labelImageBase.setObjectName("labelImageBase")
        self.sliderY = QtWidgets.QSlider(self.centralwidget)
        self.sliderY.setGeometry(QtCore.QRect(0, 70, 131, 22))
        self.sliderY.setMouseTracking(False)
        self.sliderY.setAccessibleName("")
        self.sliderY.setMaximum(200)
        self.sliderY.setSingleStep(1)
        self.sliderY.setProperty("value", 100)
        self.sliderY.setTracking(True)
        self.sliderY.setOrientation(QtCore.Qt.Horizontal)
        self.sliderY.setInvertedAppearance(False)
        self.sliderY.setInvertedControls(False)
        self.sliderY.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.sliderY.setTickInterval(10)
        self.sliderY.setObjectName("sliderY")
        self.sliderCb = QtWidgets.QSlider(self.centralwidget)
        self.sliderCb.setGeometry(QtCore.QRect(0, 110, 131, 22))
        self.sliderCb.setMouseTracking(False)
        self.sliderCb.setAccessibleName("")
        self.sliderCb.setMaximum(200)
        self.sliderCb.setProperty("value", 100)
        self.sliderCb.setTracking(True)
        self.sliderCb.setOrientation(QtCore.Qt.Horizontal)
        self.sliderCb.setInvertedAppearance(False)
        self.sliderCb.setInvertedControls(False)
        self.sliderCb.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.sliderCb.setTickInterval(10)
        self.sliderCb.setObjectName("sliderCb")
        self.sliderCr = QtWidgets.QSlider(self.centralwidget)
        self.sliderCr.setGeometry(QtCore.QRect(0, 150, 131, 22))
        self.sliderCr.setMouseTracking(False)
        self.sliderCr.setAccessibleName("")
        self.sliderCr.setMaximum(200)
        self.sliderCr.setProperty("value", 100)
        self.sliderCr.setTracking(True)
        self.sliderCr.setOrientation(QtCore.Qt.Horizontal)
        self.sliderCr.setInvertedAppearance(False)
        self.sliderCr.setInvertedControls(False)
        self.sliderCr.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.sliderCr.setTickInterval(10)
        self.sliderCr.setObjectName("sliderCr")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 90, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 170, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.valueLabelY = QtWidgets.QLabel(self.centralwidget)
        self.valueLabelY.setGeometry(QtCore.QRect(40, 90, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.valueLabelY.setFont(font)
        self.valueLabelY.setObjectName("valueLabelY")
        self.valueLabelCb = QtWidgets.QLabel(self.centralwidget)
        self.valueLabelCb.setGeometry(QtCore.QRect(40, 130, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.valueLabelCb.setFont(font)
        self.valueLabelCb.setObjectName("valueLabelCb")
        self.valueLabelCr = QtWidgets.QLabel(self.centralwidget)
        self.valueLabelCr.setGeometry(QtCore.QRect(40, 170, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.valueLabelCr.setFont(font)
        self.valueLabelCr.setObjectName("valueLabelCr")
        self.labelImage_Y = QtWidgets.QLabel(self.centralwidget)
        self.labelImage_Y.setGeometry(QtCore.QRect(140, 240, 220, 220))
        self.labelImage_Y.setFrameShape(QtWidgets.QFrame.Panel)
        self.labelImage_Y.setText("")
        self.labelImage_Y.setScaledContents(False)
        self.labelImage_Y.setWordWrap(False)
        self.labelImage_Y.setObjectName("labelImage_Y")
        self.labelImage_Cb = QtWidgets.QLabel(self.centralwidget)
        self.labelImage_Cb.setGeometry(QtCore.QRect(370, 240, 220, 220))
        self.labelImage_Cb.setFrameShape(QtWidgets.QFrame.Panel)
        self.labelImage_Cb.setText("")
        self.labelImage_Cb.setScaledContents(False)
        self.labelImage_Cb.setWordWrap(False)
        self.labelImage_Cb.setObjectName("labelImage_Cb")
        self.labelImage_Cr = QtWidgets.QLabel(self.centralwidget)
        self.labelImage_Cr.setGeometry(QtCore.QRect(600, 240, 220, 220))
        self.labelImage_Cr.setFrameShape(QtWidgets.QFrame.Panel)
        self.labelImage_Cr.setText("")
        self.labelImage_Cr.setScaledContents(False)
        self.labelImage_Cr.setWordWrap(False)
        self.labelImage_Cr.setObjectName("labelImage_Cr")
        self.labelImage_YCbCr = QtWidgets.QLabel(self.centralwidget)
        self.labelImage_YCbCr.setGeometry(QtCore.QRect(370, 0, 220, 220))
        self.labelImage_YCbCr.setFrameShape(QtWidgets.QFrame.Panel)
        self.labelImage_YCbCr.setText("")
        self.labelImage_YCbCr.setScaledContents(False)
        self.labelImage_YCbCr.setWordWrap(False)
        self.labelImage_YCbCr.setObjectName("labelImage_YCbCr")
        self.labelImageResult = QtWidgets.QLabel(self.centralwidget)
        self.labelImageResult.setGeometry(QtCore.QRect(600, 0, 220, 220))
        self.labelImageResult.setFrameShape(QtWidgets.QFrame.Panel)
        self.labelImageResult.setText("")
        self.labelImageResult.setScaledContents(False)
        self.labelImageResult.setWordWrap(False)
        self.labelImageResult.setObjectName("labelImageResult")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(180, 220, 141, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(460, 220, 41, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(640, 220, 141, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(240, 460, 21, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(480, 460, 21, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(710, 460, 21, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        RGB_2_YCbCr_2_RGB.setCentralWidget(self.centralwidget)

        self.retranslateUi(RGB_2_YCbCr_2_RGB)
        QtCore.QMetaObject.connectSlotsByName(RGB_2_YCbCr_2_RGB)

    def retranslateUi(self, RGB_2_YCbCr_2_RGB):
        _translate = QtCore.QCoreApplication.translate
        RGB_2_YCbCr_2_RGB.setWindowTitle(_translate("RGB_2_YCbCr_2_RGB", "RGB_2_YCbCr_2_RGB"))
        self.pushButton_selectF.setText(_translate("RGB_2_YCbCr_2_RGB", "Выбрать картинку"))
        self.pushButton_rgb2ycbcr.setText(_translate("RGB_2_YCbCr_2_RGB", "RGB_2_YCbCr"))
        self.pushButton_ycbcr2rgb.setText(_translate("RGB_2_YCbCr_2_RGB", "YCbCr_2_RGB"))
        self.label.setText(_translate("RGB_2_YCbCr_2_RGB", "Y"))
        self.label_2.setText(_translate("RGB_2_YCbCr_2_RGB", "Cb"))
        self.label_3.setText(_translate("RGB_2_YCbCr_2_RGB", "Cr"))
        self.valueLabelY.setText(_translate("RGB_2_YCbCr_2_RGB", "100"))
        self.valueLabelCb.setText(_translate("RGB_2_YCbCr_2_RGB", "100"))
        self.valueLabelCr.setText(_translate("RGB_2_YCbCr_2_RGB", "100"))
        self.label_4.setText(_translate("RGB_2_YCbCr_2_RGB", "Исходное изображение"))
        self.label_5.setText(_translate("RGB_2_YCbCr_2_RGB", "YCbCr"))
        self.label_6.setText(_translate("RGB_2_YCbCr_2_RGB", "Итоговое изображение"))
        self.label_7.setText(_translate("RGB_2_YCbCr_2_RGB", "Y"))
        self.label_8.setText(_translate("RGB_2_YCbCr_2_RGB", "Cb"))
        self.label_9.setText(_translate("RGB_2_YCbCr_2_RGB", "Cr"))
